name: Create tmkms Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release from'
        required: false
        default: v0.14.0

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout iqlusioninc/tmkms repository with tag
        run: |
          git clone https://github.com/iqlusioninc/tmkms
          cd tmkms
          git branch
          git tag
          git checkout ${{ inputs.tag }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libudev-dev  && sudo apt install libusb-1.0-0-dev

      - name: Build tmkms binary
        run: |
          cd tmkms
          ls -lah
          cargo build --features=yubihsm-server,ledger,softsign --release

      - name: Upload tmkms binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tmkms
          path: target/release/tmkms

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: Release ${{ inputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/tmkms
          asset_name: tmkms
          asset_content_type: application/octet-stream
