name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}  # Checkout the tag

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libudev-dev

      - name: Build tmkms binary
        run: cargo build --release

      - name: Upload tmkms binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tmkms
          path: target/release/tmkms

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}  # Use the pushed tag
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/tmkms
          asset_name: tmkms
          asset_content_type: application/octet-stream
